<a href="https://colab.research.google.com/github/Saqibaqeel/AIML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("numpy")

numpy


In [2]:
import numpy as np



numpy array


In [3]:
a=np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

creating n-dimension array or 2D array using numpy

In [4]:
multiArr=np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(multiArr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


the above array is 5 col and 2 row

how to create floating point or differnt type of array in numpy

In [6]:
d=np.array([1,2,3,4],dtype=float)
print(d)


[1. 2. 3. 4.]


initai place holder in numpy array

In [7]:
zer=np.zeros([(3),(3)])
print(zer)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


the above array all the intitial vallue is zero with 3 row and 3 col

In [8]:
#create array of particular value using full function
particular=np.full((3,5),6)
print(particular)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


The above parameter first we mention no. of row and col and after bracket we can mention the value of array i.e 6

creating i identity matrix using eye() function
identity matrix is a matrix in which all the value will b zeor accept princple diagonal and no. of row and no. of will be same so now need to mention no. of row and column

In [9]:
#creating a 6 by 6 identity matrix
identity=np.eye(6)
print(identity)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [12]:
#crating a random value matrix wit 3 row an 4 col
ren=np.random.random((3,4))
print(ren)

[[0.55078452 0.97597987 0.1886569  0.31098966]
 [0.05662577 0.27885687 0.70557914 0.1318177 ]
 [0.47869295 0.40265499 0.59006813 0.13845863]]


creating a random matrix with specific range

In [14]:
specificRange=np.random.randint(10,15,(3,4))#here 3 and 4 are no. of row and col and 10 15 are range
print(specificRange)

[[10 13 13 14]
 [11 10 13 12]
 [10 12 11 11]]
